export const INTRODUCTION_PAGE = 'IntroductionPage'
export const TRAVEL_DETAILS_PAGE = 'TravelDetailsPage'
export const DEPARTED_COUNTRIES_PAGE = 'DepartedCountriesPage'
export const SUMMARY_PAGE = 'SummaryPage'
export const CONFIRMATION_PAGE = 'ConfirmationPage'